config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  # http://localhost:3000/rails/info/routes show all routes
  resources :posts do 
    resources :comments
  end 
  
  get "posts", to: "posts#index"
  get "dashboard", to: "dashboard#index" 
  get "info", to: "info#index"
  get "rules", to: "rules#index"
  get "admins", to: "admins#index" 
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_post   
  before_action :find_comment, only: [:edit, :update, :destroy]
    def create
      @comment = @post.comments.create(comment_params)
      @comment.user_id = current_user[:id];

      if @comment.save 
        flash[:notice] = "Comment successfully created."
        redirect_to post_path(@post)
      else
        render 'new'
      end
    end
    def edit 
      
    end 
    def update 
        if @comment.update(comment_params)
          redirect_to post_path(@post)
        else 
          render 'edit'
        end
    end
    def destroy
        @comment.destroy
        redirect_to post_path(@post)
    end
    private

        def comment_params
            params.require(:comment).permit(:content)
        end 

        def find_post
            @post = Post.find(params[:post_id])
        end
        def find_comment 
            @comment = @post.comments.find(params[:id])
        end 
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
 
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
    def index

    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :find_post, only: [:show, :edit, :update, :destroy]

    def index
      @posts = Post.all.order("created_at DESC")
    end 
      
    def show
      @post = Post.find(params[:id])
    end
    
    def new 
     @post = current_user.posts.build
    end 

    def create
       @post = current_user.posts.build(post_params)
      if @post.save
        flash[:notice] = "Post was successfully created." 
        redirect_to @post
      else 
        render 'new'
      end
    end
    # ############################### #
    # ######### ADMIN ONLY ########## #
    # # Functions intended only for # #
    # # users with admin privelages # # 
    # ######### ADMIN ONLY ########## #
    # ############################### #
    def edit
    @post = Post.find(params[:id])
    end 

    def update
      if @post.update(post_params)
        redirect_to post_path
      else 
        render :edit
      end
    end 

    def destroy
        @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path
    end
    # ############################### #
    # ##### ADMIN FUNCTIONS END ##### #
    # ############################### #
    private 

      def post_params
        params.require(:post).permit(:title, :description)
      end

      def find_post
        @post = Post.find(params[:id])
      end
end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
  def index 

  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/views/admins/index.html.erb
<h1>Admin Dashboard</h1>



<div>
  <%= link_to "Go Home", root_path %>
</div>

app/views/comments/_comment.html.erb
<p><%= comment.content %></p>
<p>Posted by 
  <%= comment.user.email %> 
  <%= %> time_ago_in_words(comment.created_at) %>
</p>



  <% if user_signed_in? %>
  <% if comment.user == current_user.id %>
    <%= link_to "Edit", edit_post_comment_path(comment.post, comment) %>
    <%  link_to "Delete", [comment.post, comment], data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure?"
    } %>

  <% end %>
<% end %>

app/views/comments/_form.html.erb
<%= simple_form_for([@post, @post.comments.build]) do |f| %>
  <%= 
    f.input :content, 
    placeholder: "Enter comment here...", 
    label:"Comment:" 
  %>
  <%= f.button :submit %>
<% end %> 

app/views/comments/edit.html.erb
<h1>Edit</h1>
<%= simple_form_for([@post, @comment]) do |f| %>
  <%= f.input :content, label: "Content" %>
  <%= f.button :submit %>
<% end %>

app/views/dashboard/index.html.erb
<h1> My Dashboard </h1>

<div>
  <%= link_to "Go Home", root_path %>
</div>      

app/views/home/index.html.erb
<h1>Welcome to Muslim Connect!</h1>
<h3>
    A message board for the discussion
    of all things Islam.
</h3>                                     

<div class="links">
            
</div>
<footer>
  <h6>Powered by Ruby on Rails</h6>
</footer>

app/views/info/index.html.erb
<h1>Information</h1>



<div>
  <%= link_to "Go Home", root_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MuslimMessageBoard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= 
            link_to "Muslim Connect", 
            root_path, class: "navbar-brand" 
          %>
        </div>
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= 
              link_to "Dashboard", 
              dashboard_path 
            %>    
          </li>
          <li class="nav-item">
            <%= 
              link_to "Discussion", 
              posts_path 
            %>
          </li>
          <li class="nav-item">
            <%= 
              link_to "Guidelines",
              rules_path 
            %>
          </li>
          <li class="nav-item">
            <%= 
              link_to "Learn More", 
              info_path 
            %> 
          </li>
        </ul>
          
          <% if user_signed_in? %>
          <p class="logout">
            
            <%=
             link_to "Log Out", destroy_user_session_path, data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}
            %>
          </p>
          <% else %>
          <p class="login">
            <%= 
            link_to "Log In",
            new_user_session_path 
            %>
          </p>
          <p>
            <%=
              link_to "Sign Up", 
              new_user_registration_path
            %>  
          </p>
        <% end %>
          <% if user_signed_in? %>
            <p class="new-post">
              <%= 
                link_to "New Post", 
                new_post_path
              %> 
            </p>
          <% end %>
        <form class="d-flex">
          <input 
            class="form-control me-2" 
            type="search" 
            placeholder="Search" 
            aria-label="Search" />
          <button 
            class="btn btn-outline-success" 
            type="submit">
              Search
          </button>
        </form>
      </div>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>
<style>
 .nav-item{
  margin-left: 20px;
 }
 .login {
  margin-right: 20px;
 }
 .logout {
   margin-right: 20px;
 }
 .new-post {
   margin-right: 20px;
 }
</style>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
  <%= f.input :title, label: "Post title: ", placeholder: "Subject..." %>
  <%= f.input :description, label: "Post: ", placeholder: "Content..." %>
  <%= f.button :submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= render "form" %>

<style>
body {
  display: flex;
  flex-direction: column;
  justify-content: center;
  text-align: center;
}
</style>

app/views/posts/index.html.erb
<h1>Recent Posts</h1>
<% @posts.each do |post| %>
  <h3><%= post.title %></h3>
  <p><%= post.description %></p>
  <%= link_to "See More", post_path(post), class: "btn btn-default" %>

<% end %>
<div>
  <%= link_to "New Post", new_post_path %>
</div>
<div>
  <%= link_to "Go Home", root_path %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>

<p><%= @post.description %></p>
<p><%= @post.created_at %></p>

<p>Posted by: 
  <%= @post.user.email  %>
  <%= time_ago_in_words(@post.created_at)%> 
</p>    

<h3>Comments:</h3>
<%= render @post.comments %>

<h3>Leave a Comment:</h3>
<%= render 'comments/form' %>

<p><%= link_to "Back",posts_path %></p>
<% if user_signed_in? %>
  <% if  @post.user_id == current_user.id %>        
    <p><%= link_to "Edit Post",edit_post_path(@post%></p>  
    <p><%= link_to "Destroy", post_path(@post), data: {
        turbo_method: :delete, 
        turbo_confirm: "Are you sure?"} %></p>
  <% end %>
<% end %> 

app/views/rules/admin_editing.html.erb
<h3>Admin Editing Guidelines </h3>
<p>
  This website (when completed) will allow users</br>
  to edit and make additions to only their own </br>
  posts . More Importantly it will allow Admins </br>
  to censor and edit any posts found to contain </br>
  content standing In violation of our Community</br>
  Guidelines and Standards of Conduct.</br></br>
  
  <p>See <%= link_to "Rules and Guidelines", rules_path %></p>
  
  We do not want to prevent people from</br>
  genuine discussion. This privelage will</br>
  allow us to censor or delete ONLY for reasons</br>
  Such as Profanity, Personal Insults, and</br>
  speech which is generally considered to</br>
  be haram, or otherwise inappropriate. </br>
  Without needing to remove the post in </br>
  It's entirety if it has legitimate info,</br>
  arguments, inquiries or anecdotes. </br></br>

  If the post has no merit at all; </br>
  Meaning it was either posted in </br>
  bad faith, or the entire content </br>
  of the post stands in violation of</br>
  our community standards, than said</br>
  Post should be deleted rather than</br>
  Edited. </br>

  NOTE: Under no circumstances should</br>
  the contents of any post be outright</br>
  altered, or censored in such a way </br>
  that changes the original meaning of</br>
  the post. Any admin found to be doing</br>
  So intentionally will be repremanded</br>
  And repeat offenders will be stripped</br>
  Of their administrative privelages. </br>

  Always remember that the duty of our </br>
  Admins Is to keep the site safe from </br>
  Those With malicious Intentions, and </br>
  to ensure all discussions remain halal.</br>
  Our duty is not to be thought police, </br> 
  And people should never be censored </br>
  due to disagreements or 'wrong-think'.</br></br>
  
  There are very specific exceptions </br> 
  Detailed in the community guidelines </br>
  Such as attempts to promote or justify </br>
  Sin/haram. Or attempts to critize the </br>
  Prophet Muhammad, Peace be upon him. </br>
  Such restrictions are required in order </br>
  To ensure this remains a safe place for</br>
  Muslims. </br></br>
</p>
<h4> 
  Please Refer to our community guidelines</br>
  For more information on the standards for</br>
  What is or is not allowed, and what would</br>
  constitute a need for censorship or deletion</br>
</h4>1

app/views/rules/index.html.erb
]<h1>Rules and Community Guidelines</h1>

<div>
  <%= link_to "Go Home", root_path %>
</div>